name: tests

on:
  push:
    branches:
      - slides
  pull_request: {}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm lint
